--- #YAML:1.0
name:               LWP-Protocol-https
version:            6.02
abstract:           Provide https support for LWP::UserAgent
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket::SSL:  1.38
    LWP::UserAgent:   6.02
    Mozilla::CA:      20110101
    Net::HTTPS:       6
    perl:             5.008008
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/gisle/libwww-perl/tree/LWP-Protocol-https/master
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
